// Message shapes shared between the crypto worker (worker.ts, running off
// the main thread per docs/DESIGN.md's "Frontend" section) and its client
// wrapper (worker-client.ts). Kept in its own module, with no worker-only or
// DOM-only imports, so the main thread can import these types without
// pulling in anything that only makes sense inside a worker.
//
// Every request carries an explicit id so the client can correlate a
// response (or a progress event) to the call that started it -- necessary
// because a single worker instance may have more than one call in flight
// conceptually (signup's three sequential derivations all go through the
// same worker), even though this module always awaits one at a time today.

export interface GenerateSignupMaterialRequest {
  readonly kind: 'generateSignupMaterial'
  readonly id: string
  readonly password: string
  /**
   * The user's uuid, generated by the caller (see uuid.ts) before this
   * request is sent -- issue #123 made this client-generated specifically
   * so it exists before signup wraps under it: POST /api/auth/register's
   * UserID field is this same value, sent as-is, not assigned by the
   * server. credentialWrapAAD binds it directly; there is no placeholder
   * AAD and no later re-wrap step.
   */
  readonly userId: string
}

/**
 * One step of a worker call's independent Argon2id derivations, reported as
 * it completes -- see recovery-code.ts's neighbor, argon2.ts, and #33's own
 * requirement for "honest progress": each step fires only once that step's
 * derivation has actually finished, never on a timer.
 *
 * `step`/`totalSteps` are plain numbers, not a literal `1 | 2 | 3` / `3` --
 * generateSignupMaterial posts 3 (wrapNewCredentials's own three
 * derivations), but completeRecovery (#128) posts a 4th, for its own
 * upfront unwrap of the RECOVERY blob (also a full Argon2id call) before it
 * delegates to that same wrapNewCredentials. A literal type would force
 * every caller to agree on one fixed count; the real count is a property of
 * which worker call is running, not of this event shape.
 */
export interface SignupProgressEvent {
  readonly kind: 'signupProgress'
  readonly id: string
  readonly step: number
  readonly totalSteps: number
  readonly label: string
}

export interface SignupMaterial {
  readonly signingPublicKey: string
  readonly wrappingPublicKey: string

  readonly salt: string
  readonly argon2Params: { memoryKiB: number; iterations: number; parallelism: number }
  readonly wrappedPrivateKeys: { nonce: string; ciphertext: string }

  readonly recoverySalt: string
  readonly recoveryArgon2Params: { memoryKiB: number; iterations: number; parallelism: number }
  readonly recoveryWrappedPrivateKeys: { nonce: string; ciphertext: string }

  readonly recoveryVerifierSalt: string
  readonly recoveryVerifierParams: { memoryKiB: number; iterations: number; parallelism: number }
  readonly recoveryVerifier: string

  /** Shown to the user once, on the recovery-code screen. Never sent to the server. */
  readonly recoveryCode: string
}

export interface GenerateSignupMaterialResponse {
  readonly kind: 'generateSignupMaterialDone'
  readonly id: string
  readonly result: SignupMaterial
}

export interface CompleteLoginRequest {
  readonly kind: 'completeLogin'
  readonly id: string
  readonly password: string
  readonly salt: string
  readonly argon2Params: { memoryKiB: number; iterations: number; parallelism: number }
  readonly wrappedPrivateKeys: { nonce: string; ciphertext: string }
  readonly userId: string
  readonly nonce: string
}

export interface CompleteLoginResponse {
  readonly kind: 'completeLoginDone'
  readonly id: string
  readonly signature: string
}

/**
 * Redeems a recovery code and issues a brand-new full credential set --
 * #128, the recovery-screen counterpart of generateSignupMaterial. Unwraps
 * RecoveryWrappedPrivateKeys (release's response, POST
 * /api/account/recovery-code/release) with the recovery-code-derived key to
 * recover the same signing/wrapping keypair signup generated, per
 * docs/DESIGN.md: recovery re-wraps existing keys under new secrets, it
 * does not rotate them (that is #62, key rotation, a separate feature). The
 * result re-wraps that same bundle under a new password-derived key and a
 * freshly generated recovery code/verifier -- PUT /api/account/recovery-code
 * per docs/DESIGN.md, "It also issues a new recovery code," so the redeemed
 * code cannot be reused.
 */
export interface CompleteRecoveryRequest {
  readonly kind: 'completeRecovery'
  readonly id: string
  readonly recoveryCode: string
  readonly recoverySalt: string
  readonly recoveryArgon2Params: { memoryKiB: number; iterations: number; parallelism: number }
  readonly recoveryWrappedPrivateKeys: { nonce: string; ciphertext: string }
  readonly userId: string
  readonly newPassword: string
}

/**
 * The mirror of SignupMaterial for a recovery reset: no public keys, since
 * #128 doesn't rotate them. Defined as the Omit rather than repeated field
 * by field, so it can't drift from what wrapNewCredentials/completeRecovery
 * (credential-material.ts) actually return -- PR #129 round 2.
 */
export type RecoveryMaterial = Omit<SignupMaterial, 'signingPublicKey' | 'wrappingPublicKey'>

export interface CompleteRecoveryResponse {
  readonly kind: 'completeRecoveryDone'
  readonly id: string
  readonly result: RecoveryMaterial
}

/**
 * #131: change a logged-in user's password. Unwraps PROFILE with
 * oldPassword (GET /api/account/credentials' current
 * salt/argon2Params/wrappedPrivateKeys) and re-wraps the same bundle under
 * newPassword plus a freshly generated recovery code -- the mirror of
 * CompleteRecoveryRequest, but unwrapping via a password rather than a
 * recovery code, and with no server round trip in between (unlike recovery,
 * which unwraps material release() already fetched from the server).
 */
export interface CompleteChangePasswordRequest {
  readonly kind: 'completeChangePassword'
  readonly id: string
  readonly oldPassword: string
  readonly salt: string
  readonly argon2Params: { memoryKiB: number; iterations: number; parallelism: number }
  readonly wrappedPrivateKeys: { nonce: string; ciphertext: string }
  readonly userId: string
  readonly newPassword: string
}

/** The result shape is identical to RecoveryMaterial -- no public keys, a freshly issued recovery code. */
export type ChangePasswordMaterial = RecoveryMaterial

export interface CompleteChangePasswordResponse {
  readonly kind: 'completeChangePasswordDone'
  readonly id: string
  readonly result: ChangePasswordMaterial
}

/**
 * Signs a new group's trust anchor and self-signed root role grant, and
 * wraps the group's freshly generated key to the caller's own X25519 public
 * key -- issue #34. Unlike every request above, this one carries NO key
 * material of its own: it relies entirely on the worker's own liveKeys
 * cache (worker.ts), populated as a side effect of a prior completeLogin
 * call in this same worker instance's lifetime. There is deliberately no
 * way to pass a private key into this request -- the whole point of
 * caching keys inside the worker rather than handing them back to the main
 * thread (see worker.ts's own module doc comment) is that the main thread
 * never holds one to pass.
 *
 * userId must match liveKeys' cached owner -- see worker.ts's own check --
 * so a caller cannot accidentally (or otherwise) sign as whichever account
 * happened to log in most recently in a worker instance reused across a
 * logout/login in the same tab.
 */
export interface SignGroupCreationRequest {
  readonly kind: 'signGroupCreation'
  readonly id: string
  readonly userId: string
  readonly groupId: string
  /** The group's freshly generated symmetric key (Generation 0), raw bytes, base64. */
  readonly groupKey: string
}

export interface SignGroupCreationResult {
  readonly trustAnchorSignature: string
  /**
   * The "GRANT#<uuid>#<YYYY-MM-DD>#<rand>" sort key the root grant is
   * signed for and must be written under -- generated client-side
   * (group.ts's generateGrantSortKey) since roleGrantPayload now signs the
   * grant's own address. See internal/crypto/group.go's RoleGrantPayload
   * for why.
   */
  readonly rootGrantSortKey: string
  readonly rootGrantSignature: string
  /**
   * The X25519-ECIES wrap of the group's Generation 0 key, to the caller's
   * own wrapping public key. Carries ephemeralPub alongside nonce/ciphertext
   * -- unlike a WrappedBlob-shaped field elsewhere in this app (a plain
   * Argon2id-derived AES-GCM wrap), an ECIES wrap cannot be unwrapped again
   * without the ephemeral public key generated for this specific wrap. See
   * models.WrappedKey (Go) / group.ts's own doc comments for the full
   * reasoning.
   */
  readonly groupKeyWrapped: { ephemeralPub: string; nonce: string; ciphertext: string }
}

export interface SignGroupCreationResponse {
  readonly kind: 'signGroupCreationDone'
  readonly id: string
  readonly result: SignGroupCreationResult
}

/**
 * Clears the worker's cached liveKeys -- posted on logout so a worker
 * instance reused across a logout/login in the same tab cannot sign
 * anything under the previous account's keys. See worker.ts's own doc
 * comment on liveKeys.  No response is posted back; this is fire-and-forget
 * the same way there is nothing meaningful to await.
 */
export interface ClearLiveKeysRequest {
  readonly kind: 'clearLiveKeys'
  readonly id: string
}

export interface WorkerErrorResponse {
  readonly kind: 'error'
  readonly id: string
  readonly message: string
  /**
   * The thrown error's `name` (e.g. 'DecryptionFailedError'), so a caller on
   * the far side of the postMessage boundary -- where the real error class
   * is lost, only plain data crosses -- can still distinguish "wrong
   * password" (a GCM auth failure inside completeLogin) from every other
   * failure. See worker-client.ts's reconstructWorkerError.
   */
  readonly errorName: string
}

export type WorkerRequest =
  | GenerateSignupMaterialRequest
  | CompleteLoginRequest
  | CompleteRecoveryRequest
  | CompleteChangePasswordRequest
  | SignGroupCreationRequest
  | ClearLiveKeysRequest

export type WorkerResponse =
  | SignupProgressEvent
  | GenerateSignupMaterialResponse
  | CompleteLoginResponse
  | CompleteRecoveryResponse
  | CompleteChangePasswordResponse
  | SignGroupCreationResponse
  | WorkerErrorResponse
