// Message shapes shared between the crypto worker (worker.ts, running off
// the main thread per docs/DESIGN.md's "Frontend" section) and its client
// wrapper (worker-client.ts). Kept in its own module, with no worker-only or
// DOM-only imports, so the main thread can import these types without
// pulling in anything that only makes sense inside a worker.
//
// Every request carries an explicit id so the client can correlate a
// response (or a progress event) to the call that started it -- necessary
// because a single worker instance may have more than one call in flight
// conceptually (signup's three sequential derivations all go through the
// same worker), even though this module always awaits one at a time today.

export interface GenerateSignupMaterialRequest {
  readonly kind: 'generateSignupMaterial'
  readonly id: string
  readonly password: string
  /**
   * The user's uuid, generated by the caller (see uuid.ts) before this
   * request is sent -- issue #123 made this client-generated specifically
   * so it exists before signup wraps under it: POST /api/auth/register's
   * UserID field is this same value, sent as-is, not assigned by the
   * server. credentialWrapAAD binds it directly; there is no placeholder
   * AAD and no later re-wrap step.
   */
  readonly userId: string
}

/**
 * One step of signup's three independent Argon2id derivations, reported as
 * it completes -- see recovery-code.ts's neighbor, argon2.ts, and #33's own
 * requirement for "honest progress": each step fires only once that step's
 * derivation has actually finished, never on a timer.
 */
export interface SignupProgressEvent {
  readonly kind: 'signupProgress'
  readonly id: string
  readonly step: 1 | 2 | 3
  readonly totalSteps: 3
  readonly label: string
}

export interface SignupMaterial {
  readonly signingPublicKey: string
  readonly wrappingPublicKey: string

  readonly salt: string
  readonly argon2Params: { memoryKiB: number; iterations: number; parallelism: number }
  readonly wrappedPrivateKeys: { nonce: string; ciphertext: string }

  readonly recoverySalt: string
  readonly recoveryArgon2Params: { memoryKiB: number; iterations: number; parallelism: number }
  readonly recoveryWrappedPrivateKeys: { nonce: string; ciphertext: string }

  readonly recoveryVerifierSalt: string
  readonly recoveryVerifierParams: { memoryKiB: number; iterations: number; parallelism: number }
  readonly recoveryVerifier: string

  /** Shown to the user once, on the recovery-code screen. Never sent to the server. */
  readonly recoveryCode: string
}

export interface GenerateSignupMaterialResponse {
  readonly kind: 'generateSignupMaterialDone'
  readonly id: string
  readonly result: SignupMaterial
}

export interface CompleteLoginRequest {
  readonly kind: 'completeLogin'
  readonly id: string
  readonly password: string
  readonly salt: string
  readonly argon2Params: { memoryKiB: number; iterations: number; parallelism: number }
  readonly wrappedPrivateKeys: { nonce: string; ciphertext: string }
  readonly userId: string
  readonly nonce: string
}

export interface CompleteLoginResponse {
  readonly kind: 'completeLoginDone'
  readonly id: string
  readonly signature: string
}

/**
 * Redeems a recovery code and issues a brand-new full credential set --
 * #128, the recovery-screen counterpart of generateSignupMaterial. Unwraps
 * RecoveryWrappedPrivateKeys (release's response, POST
 * /api/account/recovery-code/release) with the recovery-code-derived key to
 * recover the same signing/wrapping keypair signup generated, per
 * docs/DESIGN.md: recovery re-wraps existing keys under new secrets, it
 * does not rotate them (that is #62, key rotation, a separate feature). The
 * result re-wraps that same bundle under a new password-derived key and a
 * freshly generated recovery code/verifier -- PUT /api/account/recovery-code
 * per docs/DESIGN.md, "It also issues a new recovery code," so the redeemed
 * code cannot be reused.
 */
export interface CompleteRecoveryRequest {
  readonly kind: 'completeRecovery'
  readonly id: string
  readonly recoveryCode: string
  readonly recoverySalt: string
  readonly recoveryArgon2Params: { memoryKiB: number; iterations: number; parallelism: number }
  readonly recoveryWrappedPrivateKeys: { nonce: string; ciphertext: string }
  readonly userId: string
  readonly newPassword: string
}

/** The mirror of SignupMaterial for a recovery reset: no public keys, since #128 doesn't rotate them. */
export interface RecoveryMaterial {
  readonly salt: string
  readonly argon2Params: { memoryKiB: number; iterations: number; parallelism: number }
  readonly wrappedPrivateKeys: { nonce: string; ciphertext: string }

  readonly recoverySalt: string
  readonly recoveryArgon2Params: { memoryKiB: number; iterations: number; parallelism: number }
  readonly recoveryWrappedPrivateKeys: { nonce: string; ciphertext: string }

  readonly recoveryVerifierSalt: string
  readonly recoveryVerifierParams: { memoryKiB: number; iterations: number; parallelism: number }
  readonly recoveryVerifier: string

  /** Shown to the user once, on the recovery-code screen. Never sent to the server. */
  readonly recoveryCode: string
}

export interface CompleteRecoveryResponse {
  readonly kind: 'completeRecoveryDone'
  readonly id: string
  readonly result: RecoveryMaterial
}

export interface WorkerErrorResponse {
  readonly kind: 'error'
  readonly id: string
  readonly message: string
  /**
   * The thrown error's `name` (e.g. 'DecryptionFailedError'), so a caller on
   * the far side of the postMessage boundary -- where the real error class
   * is lost, only plain data crosses -- can still distinguish "wrong
   * password" (a GCM auth failure inside completeLogin) from every other
   * failure. See worker-client.ts's reconstructWorkerError.
   */
  readonly errorName: string
}

export type WorkerRequest =
  GenerateSignupMaterialRequest | CompleteLoginRequest | CompleteRecoveryRequest

export type WorkerResponse =
  | SignupProgressEvent
  | GenerateSignupMaterialResponse
  | CompleteLoginResponse
  | CompleteRecoveryResponse
  | WorkerErrorResponse
