// Message shapes shared between the crypto worker (worker.ts, running off
// the main thread per docs/DESIGN.md's "Frontend" section) and its client
// wrapper (worker-client.ts). Kept in its own module, with no worker-only or
// DOM-only imports, so the main thread can import these types without
// pulling in anything that only makes sense inside a worker.
//
// Every request carries an explicit id so the client can correlate a
// response (or a progress event) to the call that started it -- necessary
// because a single worker instance may have more than one call in flight
// conceptually (signup's three sequential derivations all go through the
// same worker), even though this module always awaits one at a time today.

export interface GenerateSignupMaterialRequest {
  readonly kind: 'generateSignupMaterial'
  readonly id: string
  readonly password: string
  /**
   * The user's uuid, generated by the caller (see uuid.ts) before this
   * request is sent -- issue #123 made this client-generated specifically
   * so it exists before signup wraps under it: POST /api/auth/register's
   * UserID field is this same value, sent as-is, not assigned by the
   * server. credentialWrapAAD binds it directly; there is no placeholder
   * AAD and no later re-wrap step.
   */
  readonly userId: string
}

/**
 * One step of a worker call's independent Argon2id derivations, reported as
 * it completes -- see recovery-code.ts's neighbor, argon2.ts, and #33's own
 * requirement for "honest progress": each step fires only once that step's
 * derivation has actually finished, never on a timer.
 *
 * `step`/`totalSteps` are plain numbers, not a literal `1 | 2 | 3` / `3` --
 * generateSignupMaterial posts 3 (wrapNewCredentials's own three
 * derivations), but completeRecovery (#128) posts a 4th, for its own
 * upfront unwrap of the RECOVERY blob (also a full Argon2id call) before it
 * delegates to that same wrapNewCredentials. A literal type would force
 * every caller to agree on one fixed count; the real count is a property of
 * which worker call is running, not of this event shape.
 */
export interface SignupProgressEvent {
  readonly kind: 'signupProgress'
  readonly id: string
  readonly step: number
  readonly totalSteps: number
  readonly label: string
}

export interface SignupMaterial {
  readonly signingPublicKey: string
  readonly wrappingPublicKey: string

  readonly salt: string
  readonly argon2Params: { memoryKiB: number; iterations: number; parallelism: number }
  readonly wrappedPrivateKeys: { nonce: string; ciphertext: string }

  readonly recoverySalt: string
  readonly recoveryArgon2Params: { memoryKiB: number; iterations: number; parallelism: number }
  readonly recoveryWrappedPrivateKeys: { nonce: string; ciphertext: string }

  readonly recoveryVerifierSalt: string
  readonly recoveryVerifierParams: { memoryKiB: number; iterations: number; parallelism: number }
  readonly recoveryVerifier: string

  /** Shown to the user once, on the recovery-code screen. Never sent to the server. */
  readonly recoveryCode: string
}

export interface GenerateSignupMaterialResponse {
  readonly kind: 'generateSignupMaterialDone'
  readonly id: string
  readonly result: SignupMaterial
}

export interface CompleteLoginRequest {
  readonly kind: 'completeLogin'
  readonly id: string
  readonly password: string
  readonly salt: string
  readonly argon2Params: { memoryKiB: number; iterations: number; parallelism: number }
  readonly wrappedPrivateKeys: { nonce: string; ciphertext: string }
  readonly userId: string
  readonly nonce: string
}

export interface CompleteLoginResponse {
  readonly kind: 'completeLoginDone'
  readonly id: string
  readonly signature: string
}

/**
 * Redeems a recovery code and issues a brand-new full credential set --
 * #128, the recovery-screen counterpart of generateSignupMaterial. Unwraps
 * RecoveryWrappedPrivateKeys (release's response, POST
 * /api/account/recovery-code/release) with the recovery-code-derived key to
 * recover the same signing/wrapping keypair signup generated, per
 * docs/DESIGN.md: recovery re-wraps existing keys under new secrets, it
 * does not rotate them (that is #62, key rotation, a separate feature). The
 * result re-wraps that same bundle under a new password-derived key and a
 * freshly generated recovery code/verifier -- PUT /api/account/recovery-code
 * per docs/DESIGN.md, "It also issues a new recovery code," so the redeemed
 * code cannot be reused.
 */
export interface CompleteRecoveryRequest {
  readonly kind: 'completeRecovery'
  readonly id: string
  readonly recoveryCode: string
  readonly recoverySalt: string
  readonly recoveryArgon2Params: { memoryKiB: number; iterations: number; parallelism: number }
  readonly recoveryWrappedPrivateKeys: { nonce: string; ciphertext: string }
  readonly userId: string
  readonly newPassword: string
}

/**
 * The mirror of SignupMaterial for a recovery reset: no public keys, since
 * #128 doesn't rotate them. Defined as the Omit rather than repeated field
 * by field, so it can't drift from what wrapNewCredentials/completeRecovery
 * (credential-material.ts) actually return -- PR #129 round 2.
 */
export type RecoveryMaterial = Omit<SignupMaterial, 'signingPublicKey' | 'wrappingPublicKey'>

export interface CompleteRecoveryResponse {
  readonly kind: 'completeRecoveryDone'
  readonly id: string
  readonly result: RecoveryMaterial
}

/**
 * #131: change a logged-in user's password. Unwraps PROFILE with
 * oldPassword (GET /api/account/credentials' current
 * salt/argon2Params/wrappedPrivateKeys) and re-wraps the same bundle under
 * newPassword plus a freshly generated recovery code -- the mirror of
 * CompleteRecoveryRequest, but unwrapping via a password rather than a
 * recovery code, and with no server round trip in between (unlike recovery,
 * which unwraps material release() already fetched from the server).
 */
export interface CompleteChangePasswordRequest {
  readonly kind: 'completeChangePassword'
  readonly id: string
  readonly oldPassword: string
  readonly salt: string
  readonly argon2Params: { memoryKiB: number; iterations: number; parallelism: number }
  readonly wrappedPrivateKeys: { nonce: string; ciphertext: string }
  readonly userId: string
  readonly newPassword: string
}

/** The result shape is identical to RecoveryMaterial -- no public keys, a freshly issued recovery code. */
export type ChangePasswordMaterial = RecoveryMaterial

export interface CompleteChangePasswordResponse {
  readonly kind: 'completeChangePasswordDone'
  readonly id: string
  readonly result: ChangePasswordMaterial
}

/**
 * Signs a new group's trust anchor and self-signed root role grant, and
 * wraps the group's freshly generated key to the caller's own X25519 public
 * key -- issue #34. Unlike every request above, this one carries NO key
 * material of its own: it relies entirely on the worker's own liveKeys
 * cache (worker.ts), populated as a side effect of a prior completeLogin
 * call in this same worker instance's lifetime. There is deliberately no
 * way to pass a private key into this request -- the whole point of
 * caching keys inside the worker rather than handing them back to the main
 * thread (see worker.ts's own module doc comment) is that the main thread
 * never holds one to pass.
 *
 * userId must match liveKeys' cached owner -- see worker.ts's own check --
 * so a caller cannot accidentally (or otherwise) sign as whichever account
 * happened to log in most recently in a worker instance reused across a
 * logout/login in the same tab.
 */
export interface SignGroupCreationRequest {
  readonly kind: 'signGroupCreation'
  readonly id: string
  readonly userId: string
  readonly groupId: string
  /** The group's freshly generated symmetric key (Generation 0), raw bytes, base64. */
  readonly groupKey: string
}

export interface SignGroupCreationResult {
  readonly trustAnchorSignature: string
  /**
   * The "GRANT#<uuid>#<YYYY-MM-DD>#<rand>" sort key the root grant is
   * signed for and must be written under -- generated client-side
   * (group.ts's generateGrantSortKey) since roleGrantPayload now signs the
   * grant's own address. See internal/crypto/group.go's RoleGrantPayload
   * for why.
   */
  readonly rootGrantSortKey: string
  readonly rootGrantSignature: string
  /**
   * The X25519-ECIES wrap of the group's Generation 0 key, to the caller's
   * own wrapping public key. Carries ephemeralPub alongside nonce/ciphertext
   * -- unlike a WrappedBlob-shaped field elsewhere in this app (a plain
   * Argon2id-derived AES-GCM wrap), an ECIES wrap cannot be unwrapped again
   * without the ephemeral public key generated for this specific wrap. See
   * models.WrappedKey (Go) / group.ts's own doc comments for the full
   * reasoning.
   */
  readonly groupKeyWrapped: { ephemeralPub: string; nonce: string; ciphertext: string }
}

export interface SignGroupCreationResponse {
  readonly kind: 'signGroupCreationDone'
  readonly id: string
  readonly result: SignGroupCreationResult
}

/**
 * Signs a role grant for another member (issue #37) -- relies on the
 * worker's own liveKeys like every other signing request. grantorGrantRef is
 * the caller's OWN current grant (GroupDetail.myGrantSortKey); the worker
 * generates the subject's new grantSortKey and returns it with the signature.
 */
export interface SignRoleGrantRequest {
  readonly kind: 'signRoleGrant'
  readonly id: string
  readonly userId: string
  readonly groupId: string
  readonly subjectUserId: string
  readonly role: 'admin' | 'ambassador' | 'member'
  readonly grantorGrantRef: string
}

export interface SignRoleGrantResult {
  readonly grantSortKey: string
  readonly signature: string
}

export interface SignRoleGrantResponse {
  readonly kind: 'signRoleGrantDone'
  readonly id: string
  readonly result: SignRoleGrantResult
}

/**
 * Signs a pin of another user's key set (issue #63) with the worker's own
 * liveKeys. Key fields are base64. The signing key set is a set; the worker
 * does not care about its order.
 */
export interface SignPinRequest {
  readonly kind: 'signPin'
  readonly id: string
  readonly userId: string
  readonly pinnedUserId: string
  readonly signingPublicKeys: readonly string[]
  readonly wrappingPublicKey: string
}

export interface SignPinResult {
  readonly pinnerSigningPublicKey: string
  readonly signature: string
}

export interface SignPinResponse {
  readonly kind: 'signPinDone'
  readonly id: string
  readonly result: SignPinResult
}

/**
 * The caller's own CURRENT signing public key, from the worker's liveKeys
 * rather than from anything the server serves (issue #63): pins and the
 * caller's own key history are checked against this.
 */
export interface GetOwnSigningKeyRequest {
  readonly kind: 'getOwnSigningKey'
  readonly id: string
  readonly userId: string
}

export interface GetOwnSigningKeyResponse {
  readonly kind: 'getOwnSigningKeyDone'
  readonly id: string
  /** Base64. */
  readonly signingPublicKey: string
}

/**
 * Signs step 1 of the invite handshake (issue #38) -- the inviter's own
 * Ed25519 signature over the invite's creation payload. Like
 * SignGroupCreationRequest, relies entirely on the worker's own liveKeys
 * cache and carries no key material of its own.
 */
export interface SignInviteCreationRequest {
  readonly kind: 'signInviteCreation'
  readonly id: string
  readonly userId: string
  readonly inviteId: string
  readonly groupId: string
  readonly expiresAt: string
}

export interface SignInviteCreationResult {
  readonly creationSignature: string
  /**
   * The inviter's own fingerprint (fingerprint.ts), for the invite-creation
   * screen to display "while the user is paying attention" and to embed in
   * the generated link's URL fragment -- see credential-material.ts's own
   * signInviteCreation doc comment.
   */
  readonly inviterFingerprint: string
  /**
   * The per-invite MAC key (invite.ts's deriveInviteMACKey), base64url
   * encoded -- also embedded in the generated link's URL fragment,
   * alongside inviterFingerprint. Never sent to any server. See
   * deriveInviteMACKey's own doc comment for what this closes.
   */
  readonly inviteMACKey: string
}

export interface SignInviteCreationResponse {
  readonly kind: 'signInviteCreationDone'
  readonly id: string
  readonly result: SignInviteCreationResult
}

/**
 * Signs step 2 of the invite handshake (issue #39) -- the invitee's own
 * Ed25519 signature over the invite's acceptance payload, binding their own
 * current Ed25519/X25519 public keys (read from liveKeys, not passed in --
 * same reasoning as every other liveKeys-backed request).
 */
export interface SignInviteAcceptanceRequest {
  readonly kind: 'signInviteAcceptance'
  readonly id: string
  readonly userId: string
  readonly inviteId: string
  /**
   * The per-invite MAC key, base64url decoded from the invite link's URL
   * fragment by the caller (AcceptInviteScreen.tsx) before this request is
   * sent -- never fetched from any server. Required: an invite link shared
   * without its fragment cannot be accepted with real proof of possession,
   * matching signInviteAcceptance's own doc comment.
   */
  readonly inviteMACKey: string
}

export interface SignInviteAcceptanceResult {
  readonly acceptanceSignature: string
  readonly inviteMAC: string
}

export interface SignInviteAcceptanceResponse {
  readonly kind: 'signInviteAcceptanceDone'
  readonly id: string
  readonly result: SignInviteAcceptanceResult
}

/**
 * Completes step 3 of the invite handshake (issue #40) -- unwraps the
 * inviter's OWN copy of the group key and re-wraps it to the invitee's
 * signed X25519 public key. ownWrappedGroupKey/ownGeneration are the
 * caller's own MEMBER# entry (from GET /api/groups, exactly like
 * DecryptGroupNamesRequest's per-group shape); inviteId/invitedUserId/
 * invitedEd25519PublicKey/invitedX25519PublicKey/inviteMAC come from
 * GET /api/invites/pending-completions, already re-verified against
 * AcceptanceSignature by the caller (see worker.ts's own completeInvite
 * handler) before this request is sent.
 *
 * inviteMAC is what this request itself DOES still need checked, and
 * deliberately cannot be checked by the caller the way the Ed25519
 * signature is: verifying it requires re-deriving k from the inviter's own
 * long-term signing seed (deriveInviteMACKey), which exists only inside
 * this worker's liveKeys cache and never crosses postMessage. See
 * credential-material.ts's completeInvite for why this MAC, not the
 * signature, is what actually proves the response came from the real
 * invitee rather than a malicious server.
 */
export interface CompleteInviteRequest {
  readonly kind: 'completeInvite'
  readonly id: string
  readonly userId: string
  readonly inviteId: string
  readonly groupId: string
  readonly ownWrappedGroupKey: { ephemeralPub: string; nonce: string; ciphertext: string }
  readonly ownGeneration: number
  readonly invitedUserId: string
  readonly invitedEd25519PublicKey: string
  readonly invitedX25519PublicKey: string
  readonly inviteMAC: string
}

export interface CompleteInviteResult {
  readonly wrappedGroupKey: { ephemeralPub: string; nonce: string; ciphertext: string }
  readonly generation: number
}

export interface CompleteInviteResponse {
  readonly kind: 'completeInviteDone'
  readonly id: string
  readonly result: CompleteInviteResult
}

/**
 * Decrypts one or more private groups' name/description for the group list
 * (issue #35) -- like signGroupCreation, relies entirely on the worker's
 * own liveKeys cache and carries no key material of its own. Each entry is
 * one member's own wrapped entry point (from their MEMBER# item) plus the
 * group's own ciphertext (from META), both already fetched by
 * GET /api/groups -- see lib/api/groups.ts's GroupListEntry, the wire shape
 * this batches from.
 *
 * Batched (an array, not one group per call) so the caller pays one
 * postMessage round trip for a whole group list rather than one per group
 * -- the group list is DESIGN.md's own "hottest read," so this avoids
 * turning a single fan-out read into a second fan-out of worker calls.
 *
 * userId must match liveKeys' cached owner, exactly like
 * SignGroupCreationRequest, for the identical reason.
 */
export interface DecryptGroupNamesRequest {
  readonly kind: 'decryptGroupNames'
  readonly id: string
  readonly userId: string
  readonly groups: readonly {
    readonly groupId: string
    /** The member's own generation -- what wrappedGroupKey is wrapped for. */
    readonly generation: number
    /** The generation the name/description ciphertext was encrypted under (the AAD). */
    readonly nameGeneration: number
    readonly wrappedGroupKey: { ephemeralPub: string; nonce: string; ciphertext: string }
    readonly nameCiphertext: { nonce: string; ciphertext: string }
    readonly descriptionCiphertext: { nonce: string; ciphertext: string }
  }[]
}

/**
 * One group's decrypt outcome. name/description are null, not a thrown
 * error, when this specific group's unwrap or decrypt fails (a stale cache
 * entry from before a key rotation this client hasn't caught up on yet, or
 * genuinely corrupt data) -- see DecryptGroupNamesResponse's own doc
 * comment for why one bad entry must not fail the whole batch.
 */
export interface DecryptedGroupName {
  readonly groupId: string
  readonly name: string | null
  readonly description: string | null
}

/**
 * One failed group's ciphertext must not blank the rest of the caller's
 * group list -- a sidebar that goes empty because one entry's key rotated
 * out from under a stale cache is a worse failure mode than that one entry
 * showing a fallback label while every other group still renders. So this
 * response is always a full-length result array, never a rejection for a
 * partial failure; per-entry null is the failure signal, not a thrown
 * WorkerErrorResponse (that's reserved for a request-level failure, e.g.
 * liveKeys being cold or belonging to a different account, same as
 * signGroupCreation).
 */
export interface DecryptGroupNamesResponse {
  readonly kind: 'decryptGroupNamesDone'
  readonly id: string
  readonly results: readonly DecryptedGroupName[]
}

/**
 * #36: seals an edited private-group name and description under the group
 * key. See credential-material.ts's encryptGroupText. Same userId/liveKeys
 * guards as DecryptGroupNamesRequest, but a failure REJECTS (there is no
 * per-entry null for a write).
 */
export interface EncryptGroupTextRequest {
  readonly kind: 'encryptGroupText'
  readonly id: string
  readonly userId: string
  readonly groupId: string
  readonly generation: number
  readonly nameGeneration: number
  readonly wrappedGroupKey: { ephemeralPub: string; nonce: string; ciphertext: string }
  readonly name: string
  readonly description: string
}

export interface EncryptGroupTextResponse {
  readonly kind: 'encryptGroupTextDone'
  readonly id: string
  readonly nameCiphertext: { nonce: string; ciphertext: string }
  readonly descriptionCiphertext: { nonce: string; ciphertext: string }
}

/**
 * Clears the worker's cached liveKeys -- posted on logout so a worker
 * instance reused across a logout/login in the same tab cannot sign
 * anything under the previous account's keys. See worker.ts's own doc
 * comment on liveKeys.  No response is posted back; this is fire-and-forget
 * the same way there is nothing meaningful to await.
 */
export interface ClearLiveKeysRequest {
  readonly kind: 'clearLiveKeys'
  readonly id: string
}

export interface WorkerErrorResponse {
  readonly kind: 'error'
  readonly id: string
  readonly message: string
  /**
   * The thrown error's `name` (e.g. 'DecryptionFailedError'), so a caller on
   * the far side of the postMessage boundary -- where the real error class
   * is lost, only plain data crosses -- can still distinguish "wrong
   * password" (a GCM auth failure inside completeLogin) from every other
   * failure. See worker-client.ts's reconstructWorkerError.
   */
  readonly errorName: string
}

export type WorkerRequest =
  | GenerateSignupMaterialRequest
  | CompleteLoginRequest
  | CompleteRecoveryRequest
  | CompleteChangePasswordRequest
  | SignGroupCreationRequest
  | SignRoleGrantRequest
  | SignPinRequest
  | GetOwnSigningKeyRequest
  | DecryptGroupNamesRequest
  | EncryptGroupTextRequest
  | SignInviteCreationRequest
  | SignInviteAcceptanceRequest
  | CompleteInviteRequest
  | ClearLiveKeysRequest

export type WorkerResponse =
  | SignupProgressEvent
  | GenerateSignupMaterialResponse
  | CompleteLoginResponse
  | CompleteRecoveryResponse
  | CompleteChangePasswordResponse
  | SignGroupCreationResponse
  | SignRoleGrantResponse
  | SignPinResponse
  | GetOwnSigningKeyResponse
  | DecryptGroupNamesResponse
  | EncryptGroupTextResponse
  | SignInviteCreationResponse
  | SignInviteAcceptanceResponse
  | CompleteInviteResponse
  | WorkerErrorResponse
