version: '3.8'

services:
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    depends_on:
      - react
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./frontend/build:/usr/share/nginx/html
    networks:
      - app-network

  react:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    working_dir: /app
    volumes:
      - ./frontend:/app
    command: npm run build
    networks:
      - app-network

  node:
    build:
      context: ./backend
      dockerfile: Dockerfile
    working_dir: /app
    volumes:
      - ./backend:/app
    command: npm start
    depends_on:
      - postgres
    environment:
      POSTGRES_USER: reliable
      # POSTGRES_PASSWORD: password
      POSTGRES_DB: trustboard
      POSTGRES_HOST: postgres
    networks:
      - app-network

  postgres:
    image: postgres:14
    environment:
      POSTGRES_USER: reliable
      # POSTGRES_PASSWORD: password
      POSTGRES_DB: trustboard
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  pgdata: