// The async body of CreateGroupScreen's handleSubmit, pulled out to a plain
// function that takes its worker/network calls as arguments -- the same
// split runSignup.ts/runRecovery.ts/runChangePassword.ts made from their
// own screens, for the same reason: this can be unit-tested directly,
// against real ApiError instances and a stubbed signGroupCreation/
// createGroup, without jsdom or a real worker.
//
// groupId and the group key are NOT generated in here, unlike runSignup's
// own userId -- CreateGroupScreen generates (or reuses, on retry) both
// itself, before calling this function, because it also needs groupId to
// build the AAD a private group's encrypted name/description are sealed
// under (groupNameAAD) before signGroupCreation is ever called. This
// function's only job is orchestration: sign, then submit.
//
// This still shares runSignup's real hazard, just one layer up: groupId and
// the group key are freshly, randomly generated by the CLIENT (see
// internal/handlers/group.go's own doc comment on why groupId must be
// client-generated), so a lost response after POST /api/groups actually
// committed cannot be safely retried by generating fresh material -- that
// would silently create a SECOND, orphaned group under a NEW id that nobody
// will ever see again. CreateGroupScreen is responsible for caching and
// reusing the exact groupId/group key/form an ambiguous failure used, the
// same reasoning PR #133 round 1 established for SignupMaterial -- this
// function just reports which failures are ambiguous via CreateGroupResult.

import { ApiError } from '@/lib/api/auth'
import type { CreateGroupRequest, CreateGroupResponse } from '@/lib/api/groups'
import type { SignGroupCreationResult } from '@/lib/crypto/worker-protocol'

export interface GroupFormInput {
  readonly visibility: 'private' | 'public'
  readonly namePlaintext?: string
  readonly descriptionPlaintext?: string
  readonly nameCiphertext?: { readonly nonce: string; readonly ciphertext: string }
  readonly descriptionCiphertext?: { readonly nonce: string; readonly ciphertext: string }
  readonly revocationMode: 'rotating' | 'open'
  readonly expirationDays: number
}

export type CreateGroupErrorKind = 'definitelyUncommitted' | 'ambiguous' | 'authRequired'

export type CreateGroupResult =
  | { readonly ok: true; readonly response: CreateGroupResponse }
  | { readonly ok: false; readonly kind: CreateGroupErrorKind; readonly error: unknown }

/**
 * Whether err is an ApiError whose status proves POST /api/groups' write
 * never ran -- mirrors runSignup's isDefinitelyUncommitted exactly.
 * internal/handlers/group.go returns every 4xx (validation, the
 * signature-verification failures, the groupId conflict) before
 * db.CreateGroup's transaction ever runs, so those definitely did not
 * commit. Only a non-ApiError (network failure) or a 5xx is genuinely
 * ambiguous about whether the group was actually created.
 */
export function isDefinitelyUncommitted(err: unknown): boolean {
  return err instanceof ApiError && err.status < 500
}

export interface CreateGroupDeps {
  readonly signGroupCreation: (req: {
    readonly userId: string
    readonly groupId: string
    readonly groupKey: string
  }) => Promise<SignGroupCreationResult>
  readonly createGroup: (req: CreateGroupRequest) => Promise<CreateGroupResponse>
  readonly userId: string
}

/**
 * Runs the create-group flow's second half: signGroupCreation (worker) ->
 * createGroup (server), against an already-fully-formed groupId, group key,
 * and form. See this file's own header comment for why groupId/groupKeyB64
 * generation lives in CreateGroupScreen instead of here.
 */
export async function runCreateGroup(
  deps: CreateGroupDeps,
  groupId: string,
  groupKeyB64: string,
  form: GroupFormInput,
): Promise<CreateGroupResult> {
  let signed: SignGroupCreationResult
  try {
    signed = await deps.signGroupCreation({ userId: deps.userId, groupId, groupKey: groupKeyB64 })
  } catch (err) {
    // Signing is a worker call, not a network request -- like
    // generateSignupMaterial, it either produces a result or it doesn't,
    // with no partial-completion/lost-response possibility a fetch has.
    return { ok: false, kind: 'definitelyUncommitted', error: err }
  }

  try {
    const response = await deps.createGroup({
      groupId,
      visibility: form.visibility,
      ...(form.namePlaintext !== undefined && { namePlaintext: form.namePlaintext }),
      ...(form.descriptionPlaintext !== undefined && {
        descriptionPlaintext: form.descriptionPlaintext,
      }),
      ...(form.nameCiphertext !== undefined && { nameCiphertext: form.nameCiphertext }),
      ...(form.descriptionCiphertext !== undefined && {
        descriptionCiphertext: form.descriptionCiphertext,
      }),
      revocationMode: form.revocationMode,
      expirationDays: form.expirationDays,
      groupKeyWrapped: signed.groupKeyWrapped,
      trustAnchorSignature: signed.trustAnchorSignature,
      rootGrantSignature: signed.rootGrantSignature,
    })
    return { ok: true, response }
  } catch (err) {
    if (err instanceof ApiError && err.status === 401) {
      // The session expired between this screen loading and submit -- same
      // classification runChangePassword/runRecovery give a 401 on their
      // own writes, routed to a re-login prompt rather than a generic
      // network error.
      return { ok: false, kind: 'authRequired', error: err }
    }
    if (isDefinitelyUncommitted(err)) {
      // Includes ErrGroupIDTaken's 409 (code: group_id_taken) -- the
      // astronomically rare collision case. Per createGroup's own doc
      // comment, that specific id is unusable, so CreateGroupScreen must
      // generate a fresh groupId (and re-encrypt under a fresh group key)
      // before retrying, not resend this exact request.
      return { ok: false, kind: 'definitelyUncommitted', error: err }
    }
    // Network failure or a 5xx: createGroup()'s write may have committed
    // even though this response was lost. CreateGroupScreen is responsible
    // for caching groupId/groupKeyB64/form so a resubmission of the SAME
    // form can resend it byte-for-byte rather than regenerating.
    return { ok: false, kind: 'ambiguous', error: err }
  }
}
