// The async body of CreateInviteScreen's handleSubmit -- issue #38, the
// same split runCreateGroup.ts's own header comment describes: this can be
// unit-tested directly, against real ApiError instances and a stubbed
// signInviteCreation/createInvite, without jsdom or a real worker.
//
// inviteId is generated by the CALLER (CreateInviteScreen), not here --
// signInviteCreation's own doc comment: the signed payload binds the
// invite id, so the client must know it before it signs, before this
// function is ever called. This function's only job is orchestration:
// sign, then submit.

import { ApiError } from '@/lib/api/auth'
import type { CreateInviteRequest, CreateInviteResponse } from '@/lib/api/invites'
import type { SignInviteCreationResult } from '@/lib/crypto/worker-protocol'

export type CreateInviteErrorKind =
  'definitelyUncommitted' | 'ambiguous' | 'authRequired' | 'forbidden'

export type CreateInviteResult =
  | {
      readonly ok: true
      readonly response: CreateInviteResponse
      /** The inviter's own fingerprint -- see signInviteCreation's own doc comment for why this is shown at exactly this moment. */
      readonly inviterFingerprint: string
      /** The per-invite MAC key, embedded in the link's fragment alongside inviterFingerprint -- see deriveInviteMACKey's own doc comment. */
      readonly inviteMACKey: string
    }
  | { readonly ok: false; readonly kind: CreateInviteErrorKind; readonly error: unknown }

/**
 * Whether err is an ApiError whose status proves
 * POST /api/groups/{groupId}/invites' write never ran -- mirrors
 * runCreateGroup's isDefinitelyUncommitted exactly. Every 4xx (validation,
 * the not-a-member/not-admin-or-ambassador 403, the signature-verification
 * failure) is returned before db.CreateInvite's transaction ever runs, so
 * those definitely did not commit. Only a non-ApiError (network failure) or
 * a 5xx is genuinely ambiguous about whether the invite was actually
 * created.
 */
export function isDefinitelyUncommitted(err: unknown): boolean {
  return err instanceof ApiError && err.status < 500
}

export interface CreateInviteDeps {
  readonly signInviteCreation: (req: {
    readonly userId: string
    readonly inviteId: string
    readonly groupId: string
    readonly expiresAt: string
  }) => Promise<SignInviteCreationResult>
  readonly createInvite: (
    groupId: string,
    req: CreateInviteRequest,
  ) => Promise<CreateInviteResponse>
  readonly userId: string
}

/**
 * Runs the create-invite flow's second half: signInviteCreation (worker) ->
 * createInvite (server), against an already-chosen inviteId/groupId/
 * expiresAt. See this file's own header comment for why inviteId
 * generation lives in CreateInviteScreen instead of here.
 *
 * Unlike runCreateGroup, there is no client-chosen secret material here to
 * lose on a lost response (no group key is generated by this flow) --
 * inviteId is the only client-chosen value, and CreateInviteScreen is
 * responsible for caching and reusing it across a retry of an ambiguous
 * failure, the same shape groupId gets in CreateGroupScreen, so a retry
 * does not orphan a first, actually-committed invite under an id nobody
 * will ever see again.
 */
export async function runCreateInvite(
  deps: CreateInviteDeps,
  inviteId: string,
  groupId: string,
  expiresAt: string,
): Promise<CreateInviteResult> {
  let signed: SignInviteCreationResult
  try {
    signed = await deps.signInviteCreation({ userId: deps.userId, inviteId, groupId, expiresAt })
  } catch (err) {
    // Signing is a worker call, not a network request -- like
    // signGroupCreation, it either produces a result or it doesn't, with
    // no partial-completion/lost-response possibility a fetch has.
    return { ok: false, kind: 'definitelyUncommitted', error: err }
  }

  try {
    const response = await deps.createInvite(groupId, {
      inviteId,
      expiresAt,
      creationSignature: signed.creationSignature,
    })
    return {
      ok: true,
      response,
      inviterFingerprint: signed.inviterFingerprint,
      inviteMACKey: signed.inviteMACKey,
    }
  } catch (err) {
    if (err instanceof ApiError && err.status === 401) {
      return { ok: false, kind: 'authRequired', error: err }
    }
    if (err instanceof ApiError && err.status === 403) {
      // Not an admin or ambassador of this group -- a genuine, definite
      // rejection, distinct from a network failure a retry might resolve.
      return { ok: false, kind: 'forbidden', error: err }
    }
    if (isDefinitelyUncommitted(err)) {
      return { ok: false, kind: 'definitelyUncommitted', error: err }
    }
    // Network failure or a 5xx: createInvite()'s write may have committed
    // even though this response was lost. CreateInviteScreen is
    // responsible for caching inviteId/expiresAt so a resubmission of the
    // same request reuses the same inviteId rather than generating a fresh
    // one -- NOT a byte-for-byte resend, though: signInviteCreation runs
    // again on every attempt including this one, re-signing under
    // whatever liveKeys happens to be live at that moment.
    return { ok: false, kind: 'ambiguous', error: err }
  }
}
