// The async body of SignupScreen's handleCredentials, pulled out to a plain
// function that takes its network/worker calls as arguments -- the same
// split runRecovery.ts and runChangePassword.ts made from their own
// screens, for the same reason: this can be unit-tested directly, against
// real ApiError instances and stubbed generateUserID/register/challenge/
// completeLogin/verify, without jsdom or a real worker.
//
// #124's real subject lives here: SignupScreen used to call generateUserID
// and generateSignupMaterial fresh on every call to handleCredentials, so a
// user who resubmits the form after register()'s response was lost (but the
// write actually committed -- see internal/db/register.go's own fix for the
// server-side half of #124) sent a *different* userId AND different key
// material on the retry. The server-side fix can only recognize "this is my
// own earlier write" when the retry's UserID matches; a client that
// regenerates the id defeats it before it ever runs.
//
// PR #133 round 1 review found that even fixing just the userId is not
// enough, and is actively dangerous: generateSignupMaterial draws fresh
// randomness on every call (salts, nonces, keypairs, and the recovery code
// itself -- see credential-material.ts's own generateRecoveryCode), keyed
// only on the password/userId as *inputs*, never as a deterministic seed.
// If the first attempt's register() actually committed, the server's
// double-failure retry check returns success without writing anything --
// so a retry that regenerated its material would show the user a brand
// new recovery code while the account is still wrapped under the FIRST
// attempt's code, which nobody ever saw. Worse, if the resubmitted password
// differs from the first attempt's (a typo fix), the retry succeeds with
// 201 but the stored blob is wrapped under the OLD password -- the
// post-register login then fails, and the user is left with a login that
// doesn't work and a recovery code that doesn't work either. Full lockout,
// strictly worse than the 409 this issue set out to fix.
//
// So `resume` now caches the entire SignupMaterial generated by the first
// attempt (not just userId), and is only reused verbatim -- generating
// nothing new -- when BOTH the username and the password match exactly
// what produced it. Any mismatch (different username, or the same username
// with a changed password) drops the pending state and runs a genuinely
// fresh attempt instead: nothing was provably committed under the NEW
// input combination, so there's nothing to resume, and a real conflict
// then correctly surfaces as a 409 rather than a silent, wrong "success".
//
// Only ambiguous failures (isDefinitelyUncommitted false: a network error or
// 5xx) produce a `resume` at all. A clean 4xx (validation, WAF, or a
// genuine username_taken/user_id_taken conflict) proves nothing committed,
// so there is nothing to retry.

import { ApiError } from '@/lib/api/auth'
import type { ChallengeResponse, RegisterRequest, VerifyResponse } from '@/lib/api/auth'
import type { SignupMaterial, SignupProgressEvent } from '@/lib/crypto/worker-protocol'

/**
 * Whether err is an ApiError whose status proves register()'s write never
 * ran -- mirrors runRecovery's/runChangePassword's isDefinitelyUncommitted
 * exactly. internal/handlers/register.go returns every 4xx (validation, the
 * closed-registration 403, the username/userId conflicts) before
 * db.Register's transaction ever runs, so those (and the WAF's 403)
 * definitely did not commit. Only a non-ApiError (network failure, a lost
 * response) or a 5xx is genuinely ambiguous about whether the account was
 * actually created.
 */
export function isDefinitelyUncommitted(err: unknown): boolean {
  return err instanceof ApiError && err.status < 500
}

export interface PendingSignup {
  readonly username: string
  readonly userId: string
  readonly password: string
  /**
   * The exact material generateSignupMaterial produced for this attempt --
   * cached, not regenerated, so a resume can resend it byte-for-byte. See
   * this file's own header comment (PR #133 round 1) for why regenerating
   * on resume is unsafe: the recovery code and every salt/nonce/keypair in
   * SignupMaterial are freshly random per call, so a "successful" retry
   * that regenerated would show the user a recovery code that doesn't match
   * what the server actually has stored from the first, possibly-committed
   * attempt.
   */
  readonly material: SignupMaterial
}

export type SignupErrorKind = 'definitelyUncommitted' | 'ambiguous'

export type SignupResult =
  | {
      readonly ok: true
      readonly material: SignupMaterial
      readonly loggedIn: boolean
    }
  | {
      readonly ok: false
      readonly kind: SignupErrorKind
      readonly error: unknown
      /**
       * Usually set only when kind is 'ambiguous' -- the caller should hold
       * onto this and pass it back in as `resume` on the next attempt if the
       * user resubmits the SAME username and password, so the retry sends
       * the exact request the first, possibly-committed attempt did (see
       * this file's own header comment on why "exact" -- not merely the
       * same userId -- is load-bearing).
       *
       * The one 'definitelyUncommitted' exception is issue #134: a
       * `username_taken` 409 whose username matches a `resume` this call
       * was passed in means an EARLIER ambiguous attempt already committed
       * under that username -- runSignup echoes that same `resume` back
       * unchanged here (never a new one; a 409 proves nothing committed
       * under the input THIS call actually used) so the caller can offer the
       * user a path back to their original password rather than silently
       * discarding the only route to the account's real recovery code. See
       * this file's own header comment below the accept-conflict-as-resume
       * branch.
       */
      readonly resume?: PendingSignup
    }

/**
 * The error message SignupScreen should show for a failed (ok: false)
 * SignupResult -- pulled out to a plain function, same as the rest of this
 * file's logic, so the issue #134 distinction below is unit-tested directly
 * rather than only reachable through a mounted SignupScreen (this project
 * has no jsdom/component-testing setup -- see this file's own header
 * comment on why runSignup itself takes its deps as plain arguments).
 *
 * Issue #134: only a 'definitelyUncommitted' result WITH a resume (the
 * username_taken-matching-a-stale-resume case -- see SignupResult's own doc
 * comment) gets the "an earlier attempt may have already created this
 * account" hint. An 'ambiguous' result also carries a `resume` -- the
 * ordinary #124/#133 retry-caching case -- but that's a network hiccup with
 * no evidence of any real prior conflict, so it keeps getting the generic
 * message instead; showing the #134 hint there would tell a user something
 * happened that this function has no actual evidence for.
 */
export function signupErrorMessage(result: Extract<SignupResult, { ok: false }>): string {
  if (result.kind === 'definitelyUncommitted' && result.resume !== undefined) {
    return 'An earlier attempt may have already created this account. Try your original password, or log in if you remember it.'
  }
  if (result.error instanceof ApiError && result.error.status !== 403) {
    return result.error.message
  }
  return 'Could not create your account. Try again.'
}

export interface SignupDeps {
  readonly generateUserID: () => string
  readonly generateSignupMaterial: (
    password: string,
    userId: string,
    onProgress: (event: SignupProgressEvent) => void,
  ) => Promise<SignupMaterial>
  readonly register: (req: RegisterRequest) => Promise<unknown>
  readonly challenge: (username: string) => Promise<ChallengeResponse>
  readonly completeLogin: (req: {
    readonly password: string
    readonly salt: string
    readonly argon2Params: { memoryKiB: number; iterations: number; parallelism: number }
    readonly wrappedPrivateKeys: { nonce: string; ciphertext: string }
    readonly userId: string
    readonly nonce: string
  }) => Promise<string>
  readonly verify: (username: string, nonce: string, signature: string) => Promise<VerifyResponse>
  readonly onProgress: (event: SignupProgressEvent) => void
  /**
   * Called with the verified userId once login after registration actually
   * succeeds -- SessionContext's session.login, injected rather than
   * imported directly so this stays a plain function callable from a test
   * without React context. Never called if the post-register login fails;
   * see SignupScreen.tsx's own header comment on why that's still an
   * `ok: true` result rather than a thrown error.
   */
  readonly onLogin: (userId: string) => void
  /**
   * Called once register() succeeds, before the post-register login is
   * attempted -- so the caller can switch its progress UI from "creating
   * your account" to "logging you in" honestly, the same transition
   * SignupScreen made inline before this was extracted.
   */
  readonly onRegistered: (material: SignupMaterial) => void
}

/**
 * Runs registration + immediate login: generateSignupMaterial (worker) ->
 * register() -> challenge -> completeLogin (worker) -> verify. See
 * SignupScreen.tsx's own header comment for why register() and the
 * post-register login are two separate try blocks -- once register()
 * succeeds the account exists server-side with a real recovery code that
 * must reach the caller regardless of what happens next, so only the first
 * try's failure can produce a SignupResult with ok: false; every path after
 * that resolves `ok: true` with `loggedIn` reflecting whether the
 * follow-up login actually worked.
 *
 * `resume`, when passed, is only actually used to SKIP generateSignupMaterial
 * and resend cached material byte-for-byte when its username AND password
 * both equal this call's arguments exactly. Any mismatch means this is not a
 * resend of the same request (a different username is a new attempt; the
 * same username with a different password means the user changed something,
 * e.g. fixing a typo), so runSignup falls back to generating fresh material
 * rather than resuming, exactly as if no `resume` had been passed. See this
 * file's own header comment (PR #133 round 1) for why this check has to be
 * exact, not just "same username": a retry that resent different material
 * could make the server's own #124 fix (internal/db/register.go) return a
 * silent 201 over a first attempt's still-live, different credentials.
 *
 * Issue #134: even when `resume` isn't reused for the request itself (a
 * changed password), it is still consulted once more if register() comes
 * back with a `username_taken` 409 for a username matching `resume`'s. That
 * combination means an EARLIER call already committed an account under this
 * username (the ambiguous failure that produced `resume` in the first
 * place), and this fresh attempt's different password just collided with
 * it -- not a real "someone else took this name" conflict. Without this
 * check, the caller has no way to distinguish the two and would discard
 * `resume` as a normal conflict, permanently losing the only path back to
 * the first attempt's recovery code (which was never sent to the server in
 * the clear and so cannot be recovered any other way). See the
 * 'definitelyUncommitted' branch below and SignupResult's own doc comment.
 */
export async function runSignup(
  deps: SignupDeps,
  username: string,
  password: string,
  resume?: PendingSignup,
): Promise<SignupResult> {
  const resuming =
    resume !== undefined && resume.username === username && resume.password === password
  const userId = resuming ? resume.userId : deps.generateUserID()

  // Generating material (a worker call, not a network request) is never
  // itself the ambiguous failure this issue is about -- either it produces
  // material or it doesn't, with no partial-completion/lost-response
  // possibility the way a fetch has. So a failure here (e.g. an OOM on a
  // low-memory phone) has no material to cache and cannot resume; only a
  // failure from register() itself, below, can.
  let material: SignupMaterial
  try {
    material = resuming
      ? resume.material
      : await deps.generateSignupMaterial(password, userId, deps.onProgress)
  } catch (err) {
    return { ok: false, kind: 'definitelyUncommitted', error: err }
  }

  try {
    await deps.register({
      username,
      userId,
      signingPublicKey: material.signingPublicKey,
      wrappingPublicKey: material.wrappingPublicKey,
      salt: material.salt,
      argon2Params: material.argon2Params,
      wrappedPrivateKeys: material.wrappedPrivateKeys,
      recoverySalt: material.recoverySalt,
      recoveryArgon2Params: material.recoveryArgon2Params,
      recoveryWrappedPrivateKeys: material.recoveryWrappedPrivateKeys,
      recoveryVerifierSalt: material.recoveryVerifierSalt,
      recoveryVerifierParams: material.recoveryVerifierParams,
      recoveryVerifier: material.recoveryVerifier,
    })
  } catch (err) {
    if (isDefinitelyUncommitted(err)) {
      // Issue #134: a username_taken 409 whose username matches a stale
      // `resume` means an earlier ambiguous attempt under that username
      // already committed -- this fresh attempt (with different material,
      // since resuming was false or it would have collided with itself
      // instead) just collided with that real account. Echo `resume`
      // back UNCHANGED rather than discarding it: nothing about THIS call
      // proves anything new committed, so there is nothing safe to update
      // it to, but the caller still needs a path back to the original
      // attempt's material for the user to reach by resubmitting the
      // ORIGINAL password. Every other definitelyUncommitted cause (closed
      // registration, validation, a userId conflict, or a username
      // conflict that doesn't match any stale `resume`) still has nothing
      // worth resuming.
      const staleResumeApplies =
        err instanceof ApiError &&
        err.status === 409 &&
        err.code === 'username_taken' &&
        resume !== undefined &&
        resume.username === username
      // exactOptionalPropertyTypes: `resume` must be omitted, not set to
      // undefined, when staleResumeApplies is false.
      return staleResumeApplies
        ? { ok: false, kind: 'definitelyUncommitted', error: err, resume }
        : { ok: false, kind: 'definitelyUncommitted', error: err }
    }
    // Network failure or a 5xx: register()'s write may have committed even
    // though this response was lost. Hand back the exact identity AND
    // material this attempt used, so a resubmission of the SAME
    // username+password can resend it byte-for-byte rather than
    // regenerating -- see this file's own header comment on why
    // regenerating is unsafe even when the userId is preserved.
    return {
      ok: false,
      kind: 'ambiguous',
      error: err,
      resume: { username, userId, password, material },
    }
  }

  // The account now exists server-side. Everything from here on is a
  // separate try: whatever happens, the caller must still get this
  // material back with ok: true -- see SignupScreen.tsx's own header
  // comment.
  deps.onRegistered(material)
  let loggedIn = false
  try {
    const ch = await deps.challenge(username)
    const signature = await deps.completeLogin({
      password,
      salt: ch.salt,
      argon2Params: ch.argon2Params,
      wrappedPrivateKeys: ch.wrappedPrivateKeys,
      userId: ch.userId,
      nonce: ch.nonce,
    })
    const result = await deps.verify(username, ch.nonce, signature)
    deps.onLogin(result.userId)
    loggedIn = true
  } catch {
    // Login failed after the account was already created -- the user can
    // always retry logging in themselves afterward with the password they
    // just chose. What must not happen is losing the recovery code over
    // this, so loggedIn stays false and the caller proceeds exactly as it
    // would have on success.
  }

  return { ok: true, material, loggedIn }
}
