package db

import (
	"context"
	"errors"
	"time"

	"github.com/aws/aws-sdk-go-v2/aws"
	"github.com/aws/aws-sdk-go-v2/feature/dynamodb/attributevalue"
	"github.com/aws/aws-sdk-go-v2/service/dynamodb"
	"github.com/aws/aws-sdk-go-v2/service/dynamodb/types"

	"github.com/pwntato/undergroundbb/internal/models"
)

// ErrGroupIDTaken is returned when the GROUP#<gid> META item already exists.
// gid is server-generated by idgen.UUID() (unlike RegisterInput's
// client-supplied UserID), so reaching this is expected to be astronomically
// rare rather than something a caller can provoke -- but Register's own
// PROFILE write shows the same "server-generated id" reasoning doesn't
// excuse skipping the condition, only changes how surprising hitting it
// would be. See ErrUserIDTaken's own doc comment for the fuller argument.
var ErrGroupIDTaken = errors.New("db: group id taken")

// CreateGroupInput is everything CreateGroup needs to create a group and its
// creator's own membership and root role grant. GroupID is server-generated
// (handlers.createGroup calls idgen.UUID(), matching every other
// server-assigned id in this schema) and passed in rather than generated
// here, so the caller can use it to build CreatorSigningPublicKey's
// signature payload (crypto.TrustAnchorPayload, crypto.RoleGrantPayload)
// before this call -- the same reason RegisterInput takes UserID rather than
// generating it, just with the id itself coming from the server instead of
// the client this time.
type CreateGroupInput struct {
	GroupID string

	CreatorUserID           string
	CreatorSigningPublicKey []byte
	// TrustAnchorSignature is the creator's signature (crypto.Sign under
	// crypto.ContextTrustAnchor, over crypto.TrustAnchorPayload) proving
	// CreatorUserID actually holds CreatorSigningPublicKey's private half.
	// This package does not itself call crypto.Verify -- see CreateGroup's
	// own doc comment for why that check belongs in the handler, ahead of
	// this call, alongside the same reasoning register.go's handler applies
	// to every other structural/cryptographic validation.
	TrustAnchorSignature []byte

	Visibility string // models.VisibilityPrivate or models.VisibilityPublic

	NamePlaintext         string              // set only when Visibility is public
	DescriptionPlaintext  string              // set only when Visibility is public
	NameCiphertext        *models.WrappedBlob // set only when Visibility is private
	DescriptionCiphertext *models.WrappedBlob // set only when Visibility is private

	RevocationMode string // models.RevocationRotating or models.RevocationOpen
	ExpirationDays int64  // 0 means "never expire"

	// GenerationKeyWrapped is the group's Generation 0 key, ECIES-wrapped to
	// the creator's own X25519 public key -- see models.Group.GenerationKeyWrapped's
	// own doc comment for why the creator's copy is stored on both META and
	// their own MEMBER# item.
	GenerationKeyWrapped models.WrappedKey

	// RootGrantSortKey is the GRANT# item's sort key
	// ("GRANT#<uuid>#<YYYY-MM-DD>#<rand>"), built by the caller via
	// idgen.DaySuffix so the same value can be used both as the signed
	// payload's grantorGrantRef for any grant issued later against this one
	// and as the actual DynamoDB sort key here -- this package does not
	// construct it, matching the "caller builds what the signature needs
	// before calling" pattern GroupID/TrustAnchorSignature already follow.
	RootGrantSortKey string
	// RootGrantSignature is the creator's self-signature (crypto.Sign under
	// crypto.ContextRoleGrant, over crypto.RoleGrantPayload with an empty
	// grantorGrantRef) over the root grant -- see models.RoleGrant's own doc
	// comment.
	RootGrantSignature []byte
}

// CreateGroup creates a group: the GROUP#<gid>/META item, the creator's own
// GROUP#<gid>/MEMBER#<uuid> item, and the self-signed root
// GROUP#<gid>/GRANT#<uuid>#<day>#<rand> item that anchors the chain of
// trust, as one TransactWriteItems -- see docs/DESIGN.md, "Roles and the
// chain of trust": "The anchor is signed by the creator at group creation."
// A group without its root grant already committed would be a group a
// client-side chain walk could never verify past its own creator, so this
// is subject to the same partial-write reasoning Register's own doc comment
// gives for signup's three-item transaction: no interruption (a timeout, a
// throttle) may leave a group without one of these ever accessible again
// through the ordinary write paths that assume the other two already exist.
//
// This package does not verify TrustAnchorSignature or RootGrantSignature --
// db is a pure data-access layer with no cryptographic policy of its own
// (matching RegisterInput's own doc comment on where structural validation
// belongs), and neither signature is a value this package could usefully
// check anyway: verifying them only proves CreatorUserID holds the private
// key behind CreatorSigningPublicKey, which every client that later reads
// this group must independently verify before trusting the anchor regardless
// of whether the server bothered to check it first (see DESIGN.md,
// "Pinning the key... matters because... anchoring on the uuid alone would
// still let the server choose"). The handler validates shape, size and
// encoding before this call, the same division register.go's handler and
// this package already use.
func (c *Client) CreateGroup(ctx context.Context, in CreateGroupInput) error {
	now := time.Now().UTC().Format(time.RFC3339)

	group := models.Group{
		Record: models.Record{
			PK:        "GROUP#" + in.GroupID,
			SK:        "META",
			Type:      "Group",
			CreatedAt: now,
		},
		CreatorUserID:           in.CreatorUserID,
		CreatorSigningPublicKey: in.CreatorSigningPublicKey,
		TrustAnchorSignature:    in.TrustAnchorSignature,
		Visibility:              in.Visibility,
		NamePlaintext:           in.NamePlaintext,
		DescriptionPlaintext:    in.DescriptionPlaintext,
		NameCiphertext:          in.NameCiphertext,
		DescriptionCiphertext:   in.DescriptionCiphertext,
		RevocationMode:          in.RevocationMode,
		ExpirationDays:          in.ExpirationDays,
		GenerationKeyWrapped:    in.GenerationKeyWrapped,
	}
	if in.Visibility == models.VisibilityPublic {
		// See docs/DESIGN.md, "Visibility": the directory entry is a sparse
		// GSI1 write present only on public groups. shard is fixed at "0" for
		// now -- the doc describes PUBLIC#<shard> fan-out as a future
		// scaling concern ("a small fixed fan-out is enough"), and #71
		// (public group directory) is what will actually read this index;
		// #34 only needs to write a shape #71 can build on without a schema
		// change later.
		group.GSI1PK = "PUBLIC#0"
		group.GSI1SK = "NAME#" + in.NamePlaintext + "#" + in.GroupID
	}

	membership := models.Membership{
		Record: models.Record{
			PK:        "GROUP#" + in.GroupID,
			SK:        "MEMBER#" + in.CreatorUserID,
			Type:      "Membership",
			CreatedAt: now,
			GSI1PK:    "USER#" + in.CreatorUserID,
			GSI1SK:    "GROUP#" + in.GroupID,
		},
		Role:            models.RoleAdmin,
		Generation:      0,
		WrappedGroupKey: in.GenerationKeyWrapped,
	}

	grant := models.RoleGrant{
		Record: models.Record{
			PK:        "GROUP#" + in.GroupID,
			SK:        in.RootGrantSortKey,
			Type:      "RoleGrant",
			CreatedAt: now,
		},
		SubjectUserID:           in.CreatorUserID,
		GrantedRole:             models.RoleAdmin,
		GrantorUserID:           in.CreatorUserID,
		GrantorSigningPublicKey: in.CreatorSigningPublicKey,
		Signature:               in.RootGrantSignature,
	}

	groupItem, err := attributevalue.MarshalMap(group)
	if err != nil {
		return err
	}
	membershipItem, err := attributevalue.MarshalMap(membership)
	if err != nil {
		return err
	}
	grantItem, err := attributevalue.MarshalMap(grant)
	if err != nil {
		return err
	}

	// groupItemIndex names the one conditional item's position, matching
	// Register's own isConditionalCheckFailure(err, itemIndex) pattern -- see
	// that function's doc comment for why position rather than a scan.
	const groupItemIndex = 0

	_, err = c.ddb.TransactWriteItems(ctx, &dynamodb.TransactWriteItemsInput{
		TransactItems: []types.TransactWriteItem{
			{
				Put: &types.Put{
					TableName:           aws.String(c.table),
					Item:                groupItem,
					ConditionExpression: aws.String("attribute_not_exists(PK)"),
				},
			},
			{Put: &types.Put{TableName: aws.String(c.table), Item: membershipItem}},
			{Put: &types.Put{TableName: aws.String(c.table), Item: grantItem}},
		},
	})
	if err != nil {
		if isConditionalCheckFailure(err, groupItemIndex) {
			return ErrGroupIDTaken
		}
		return err
	}
	return nil
}
